### ISSUE TITLE
GPG batch mode fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by damacus** [sous-chefs/gpg#12]
### Cookbook version

`master`

### Platform Details

`Ubuntu 18.04`

### Scenario:

Do anything in batch mode with `--no-tty` on Ubuntu. GPG still asks for a password.

This looks like the tracking issue (or something similar on debian.org

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735241

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by liaden** [comment]
This is converge successfully for me, but it obviously needs some cleanup: https://github.com/sous-chefs/gpg/compare/master...liaden:bionic-fixes?expand=1

**Comment by damacus** [comment]
could you drop us a PR with the fix in and we'll get it tested and released :)

**Comment by damacus** [comment]
fixed by #20
