### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by liaden** [sous-chefs/gpg#19]
There are several PRs that have been merged since the last release was made. Is the cookbook ready for a new release? 

I am running on bionic so https://github.com/sous-chefs/gpg/issues/12 is relatively important for me.

**Comment by damacus** [comment]
Yeah this doesn't really work right now, and Bionic made everything a bit hard. If you have an idea of a good way to make this work. I'm all ears. Right now the documentation in GPG2 doesn't match what it does. So it's a bit stuck in limbo.
